# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12\x04shop\"\x07\n\x05\x45mpty\"H\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x11\n\tpurchased\x18\x04 \x01(\x08\"6\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\" \n\x12ReadProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"U\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x11\n\tpurchased\x18\x04 \x01(\x08\"\"\n\x14\x44\x65leteProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x15\n\x13ListProductsRequest\"7\n\x14ListProductsResponse\x12\x1f\n\x08products\x18\x01 \x03(\x0b\x32\r.shop.Product2\xbe\x02\n\x0bShopService\x12:\n\rCreateProduct\x12\x1a.shop.CreateProductRequest\x1a\r.shop.Product\x12\x36\n\x0bReadProduct\x12\x18.shop.ReadProductRequest\x1a\r.shop.Product\x12:\n\rUpdateProduct\x12\x1a.shop.UpdateProductRequest\x1a\r.shop.Product\x12\x38\n\rDeleteProduct\x12\x1a.shop.DeleteProductRequest\x1a\x0b.shop.Empty\x12\x45\n\x0cListProducts\x12\x19.shop.ListProductsRequest\x1a\x1a.shop.ListProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_PRODUCT']._serialized_start=29
  _globals['_PRODUCT']._serialized_end=101
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=103
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=157
  _globals['_READPRODUCTREQUEST']._serialized_start=159
  _globals['_READPRODUCTREQUEST']._serialized_end=191
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=193
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=278
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=280
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=314
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=316
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=337
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=339
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=394
  _globals['_SHOPSERVICE']._serialized_start=397
  _globals['_SHOPSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
